name: Pull Request Management

on:
  pull_request:

jobs:
  check_yarn_cache:
    name: "🔍 Check Yarn Cache"
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
          - macos-latest
        nodes:
          - 12
          - 14
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@2
        with:
          key: ${{ runner.os }}-${{ matrix.node }}-modules
          path: |
            .yarn/
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
      - run: yarn install --check-cache
